services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/app/crawly/
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/app.conf:/etc/nginx/conf.d/app.conf
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8.0.2-fpm-alpine
    container_name: php-8.0.2
    volumes:
      - ./:/app/crawly/


  
