services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/app/crawly/
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/app.conf:/etc/nginx/conf.d/app.conf
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
  composer:
    image: composer
    container_name: php-composer
    environment:
      - COMPOSER_CACHE_DIR=/etc/cache/composer
    restart: 'no'
    volumes:
      - ./:/app/
    command: ['install']
  php:
    image: php:8.0.2-fpm-alpine
    container_name: php-8
    restart: 'no'
    volumes:
      - ./:/app/crawly/